package controller;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Stack;

import model.Connections;
import model.Tab;
import model.TabList;
import view.AtTheRate;
import view.CloseBracket;
import view.DoubleBar;
import view.GreaterThan;
import view.Icons;
import view.LessThan;
import view.OpenBracket;

/**
 * This class does the compilation of the visual diagram, here DFS traversal is
 * performed and Stack is used to verify the connected diagrams.
 * 
 * @author Mayank Kataruka
 * @version 1.0
 * @author Parikshith Kedilaya Mallar
 * @version 1.1
 * 
 */

public class NodeCompiler {

	private String errorMessage = "";

	/**
	 * This method creates an adjacency list of all the nodes present in the graph.
	 */
	public void createAdjacencyList() {
		Tab tab = TabList.getInstance().getTab();
		if (!checkIconCount()) {
			tab.getWorkspace().displayMessage("Compilation Error: " + errorMessage);
			return;
		}
		LinkedHashMap<Icons, LinkedList<Icons>> adjList = new LinkedHashMap<Icons, LinkedList<Icons>>();
		List<Connections> connectionList = tab.getConnectionList();
		HashMap<Icons, Double> atTheRateLoc = new HashMap<Icons, Double>();
		for (Connections connection : connectionList) {
			Icons originIcon = connection.getOriginIcon();
			Icons destIcon = connection.getDestIcon();
			if (!adjList.containsKey(originIcon)) {
				LinkedList<Icons> list = new LinkedList<Icons>();
				list.add(destIcon);
				adjList.put(originIcon, list);
				if (originIcon instanceof AtTheRate)
					atTheRateLoc.put(originIcon, connection.getOriginPoint().getY());
			} else {
				LinkedList<Icons> list = adjList.get(originIcon);
				if (originIcon instanceof AtTheRate) {
					double getprevY = atTheRateLoc.get(originIcon);
					double getnewY = connection.getOriginPoint().getY();
					if (getnewY > getprevY)
						list.addFirst(destIcon);
					else
						list.add(destIcon);
				} else {
					list.add(destIcon);
				}
			}
		}

		for (Map.Entry<Icons, LinkedList<Icons>> map : adjList.entrySet()) {
			Icons key = map.getKey();
			if (key instanceof AtTheRate) {
				List<Icons> icon = map.getValue();
				if (icon.size() != 2) {
					tab.getWorkspace().displayMessage("Compilation Error: Loop missing @");
					return;
				}
			}
		}

		Stack<Icons> stack = new Stack<Icons>();
		Icons start = getStartIcon(adjList);
		traverse(adjList, start, stack);
		for (Icons icon : tab.getIconList()) {
			icon.setFirstConnection(false);
		}

		if (!stack.isEmpty() || start == null) {
			if (start == null) {
				errorMessage = "One or more connections missing";
			}
			tab.getWorkspace().displayMessage("Compilation Error. " + errorMessage);
		} else {
			tab.getWorkspace().displayMessage("Compilation Success");
		}
	}

	/**
	 * This method traverses through all the nodes and checks for multiple rules.
	 * This method follows Depth First Search algorithm
	 * 
	 * @param adjList - Adjacency list generated in createAdjacencyList()
	 * @param start   - starting node generated by getStartIcon()
	 * @param stack   - Stack of containing nodes.
	 */
	private void traverse(LinkedHashMap<Icons, LinkedList<Icons>> adjList, Icons start, Stack<Icons> stack) {

		if (!stack.isEmpty() && start instanceof CloseBracket && stack.peek() instanceof OpenBracket) {
			stack.pop();
			return;
		}
		if (start instanceof CloseBracket) {
			return;
		}

		List<Icons> list = adjList.get(start);

		if (list == null)
			return;

		if (start instanceof OpenBracket || start instanceof LessThan)
			stack.push(start);

		if (!stack.isEmpty() && start.isFirstConnection() && start instanceof GreaterThan
				&& stack.peek() instanceof LessThan) {
			stack.pop();
		}
		if (!stack.isEmpty() && start.isFirstConnection() && start instanceof AtTheRate
				&& stack.peek() instanceof AtTheRate) {
			stack.pop();
			return;
		}

		if (start.isFirstConnection() && start instanceof DoubleBar) {
			return;
		}

		if (start instanceof AtTheRate && !start.isFirstConnection()) {
			stack.push(start);
			start.setFirstConnection(true);
		}

		if (start instanceof DoubleBar && !start.isFirstConnection()) {
			start.setFirstConnection(true);
		}
		if (start instanceof GreaterThan && !start.isFirstConnection()) {
			start.setFirstConnection(true);
			return;
		}
		for (Icons icon : list) {

			traverse(adjList, icon, stack);
		}
	}

	/**
	 * This method finds the start icon for the node traversal
	 * 
	 * @param adjList - Adjacency list generated in createAdjacencyList()
	 * @return
	 */
	private Icons getStartIcon(LinkedHashMap<Icons, LinkedList<Icons>> adjList) {
		Icons start = null;
		int countStartIcons = 0;
		for (Entry<Icons, LinkedList<Icons>> map : adjList.entrySet()) {
			Icons key = map.getKey();
			if (key instanceof OpenBracket) {
				start = key;
				countStartIcons++;
			}
		}
		if (countStartIcons >= 2) {
			errorMessage = "More than 1 open bracket or close bracket";
			return null;
		}
		return start;
	}

	/**
	 * This method checks if there are multiple open/close brackets.
	 * 
	 * @return
	 */
	private boolean checkIconCount() {
		int countOpenBracket = 0, countCloseBracket = 0;
		Tab tab = TabList.getInstance().getTab();
		if (tab.getIconList().size() == 0) {
			errorMessage = "Nothing to compile!";
			return false;
		}
		for (Icons icon : tab.getIconList()) {
			if (icon instanceof OpenBracket) {
				countOpenBracket++;
			} else if (icon instanceof CloseBracket) {
				countCloseBracket++;
			}
		}
		if (countCloseBracket > 1 || countOpenBracket > 1) {
			errorMessage = "More than one open or close brackets";
			return false;
		}
		return true;
	}

}
